### ISSUE TITLE
Linear regression with R

### ISSUE THREAD

**Issue by smcclatchy** [smcclatchy/studyGroup#12]
Learn how to fit a linear regression model in R and produce a summary of the model. We will learn to use the lm() and summary() commands, and will plot data and linear models with the ggplot package. We'll meet on Thursday, June 9 in B53 ERB 2519 from 2 to 3pm. Bring a laptop with R and RStudio installed. Beginners welcome.
https://myjax-p.jax.org/Facilities/Maps/ResearchLabMap.pdf
Google Hangout:

**Comment by Raeurban** [comment]
Susan,

I don’t know R; I didn’t attend the workshop you had a while ago.  Can I still attend?

Also, what day is this?

Thanks,
Rae

**Comment by smcclatchy** [comment]
Hi Rae,

Beginners are welcome! Please ask IT to install R [1] and RStudio [2] before coming on Thursday, June 9 at 11am in ERB 2519. 

Thanks.

Sue

[1] https://cran.r-project.org/
[2] https://www.rstudio.com/products/RStudio/#Desktop

**Comment by smcclatchy** [comment]
Hi again,

I moved this session to the afternoon so that it doesn't conflict with Gareth Howell's promotion seminar.

Sue

**Comment by smcclatchy** [comment]
Looking forward to a fun work-along today!
