### ISSUE TITLE
Hacky Hour at Blaze, 4:30 to 6pm, Fri Sept 9

### ISSUE THREAD

**Issue by smcclatchy** [smcclatchy/studyGroup#21]
Hacky Hour is an informal way to meet other researchers, talk about projects and ideas, and build community. All are welcome!

The overall goal of this group is to build a self-sufficient community of coders and analysts with the skills, knowledge, and support to approach new questions and methods in biomedical research. We'll achieve this through formal, structured training events and through informal meetups like this one.

Let's meet on Friday, September 9th at Blaze, 198 Main St, Bar Harbor from 4:30 to 6pm.
Newcomers are especially welcome!

**Comment by kylescotshank** [comment]
Howdy Sue! 

I think Ben over at MDIBL just asked you to add me to the mailing list. I'm sorry I can't make this get-together, but I'll absolutely make it over to some of the other upcoming events/Hacky Hours!
