### ISSUE TITLE
Linux Bootcamp

### ISSUE THREAD

**Issue by smcclatchy** [smcclatchy/studyGroup#23]
Learn command line skills for high performance computing in this one-day bootcamp. We'll start with command line basics and work up to best practices for high performance computing on the cluster. 
We'll meet in room TBD at JAX Genomic Medicine on Friday, December 16 from 9am to 5pm.

This workshop is only open to JAX personnel. Please register here:
https://www.eventbrite.com/e/linux-bootcamp-tickets-28917911251

**Comment by susan-sheehan** [comment]
Can I attend this via VTC, from BH?

**Comment by smcclatchy** [comment]
Hi @susan-sheehan ,
I'll refer this to @williamssanders 
I think this would work in this case because I can be there with you in case things aren't working. Otherwise, we plan to bring this to Bar Harbor later.

**Comment by williamssanders** [comment]
Hi again Susan!

We can definitely give it a shot with Sue there to help you out if needed, and like Sue mentioned, we'll be planning to bring this to Bar Harbor in the future as well.

In the meantime, if you need any help getting up and running on either of the JAX clusters, please let me know, and I'll be glad to set something up with you.

**Comment by susan-sheehan** [comment]
Great, thanks  I'll reach out if I feel as if I got stuck.

Susan Sheehan
Korstanje Lab Manager
The Jackson Laboratory
600 Main Street
Bar Harbor, ME 04609
www.jax.orghttp://www.jax.org/

susan.sheehan@jax.orgmailto:sutphin@gmail.com
phone: (207) 288-6997

The Jackson Laboratory: Leading the search for tomorrow's cures

**Comment by smcclatchy** [comment]
Date change to Friday, Dec. 16
