### ISSUE TITLE
Data Carpentry Genomics

### ISSUE THREAD

**Issue by smcclatchy** [smcclatchy/studyGroup#25]
Data Carpentry workshops are for any researcher who has data they want to analyze , and no prior computational experience is required. This hands-on workshop teaches basic concepts, skills and tools for working more effectively with data.

The focus of this two-day workshop will be on working with genomics data and data management and analysis for genomics research. We will cover connecting to and using cloud computing and the command line for sequence quality control and bioinformatics workflows. We will not be teaching any particular bioinformatics tools, but the foundational skills that will allow you to conduct any analysis and analyze the output of a genomics pipeline.

Participants should bring their laptops and plan to participate actively. By the end of the workshop learners should be able to more effectively manage and analyze data and be able to apply the tools and approaches directly to their ongoing research. Participants will learn to analyze high-throughput (NGS) sequence data with:

• Unix command line basics
• Sequence experiment planning & quality control
• Genome alignment & cleanup
• Variant calling
• Workflow automation

Please register on the workshop website.
https://smcclatchy.github.io/2017-02-09-farmington/

Beginners are welcome!

We meet in the Holt Conference Room on Thursday and Friday, February 9-10 from 9am to 5pm.
Bring a laptop with the following software installed BEFORE the workshop:

Mac users

```
Java https://www.java.com/en/download/
Filezilla https://filezilla-project.org/download.php?show_all=1
Integrative Genomics Viewer (IGV) https://www.broadinstitute.org/igv
```

Windows users

```
Putty http://www.putty.org/ Download putty.exe.
Java https://www.java.com/en/download/
Filezilla https://filezilla-project.org/download.php?show_all=1
Integrative Genomics Viewer (IGV) https://www.broadinstitute.org/igv
```

**Comment by CaraDataExplora** [comment]
Is this workshop still running?

**Comment by smcclatchy** [comment]
Hi @CaraDataExplora,
Yes, it's running but is full.
https://smcclatchy.github.io/2017-02-09-farmington/
You can join the waiting list if you like.

Thanks.
