### ISSUE TITLE
Register Page missing

### ISSUE THREAD

**Issue by jgardin** [smcclatchy/studyGroup#31]
![image](https://cloud.githubusercontent.com/assets/22218690/21956438/a98c1fd0-da4e-11e6-87c3-18c18fca28cb.png)

I am getting a 404 when trying to register for the Feb-16th event at Jax.

**Comment by smcclatchy** [comment]
@jgardin Please try again. If it stills gives you a 404 error you can register directly at Eventbrite.
https://www.eventbrite.com/e/software-carpentry-r-for-reproducible-research-tickets-31162152838

**Comment by jgardin** [comment]
I still get the 404, but was able to register on the eventbrite website.
Thanks for the quick response.

Justin Gardin
Stony Brook University - Futcher Laboratory
347-358-2519
justin.gardin@gmail.com
