### ISSUE TITLE
Bioconductor Workshop

### ISSUE THREAD

**Issue by smcclatchy** [smcclatchy/studyGroup#75]
This one-day workshop will teach differential expression analysis  and variant annotation using R and BioConductor. The workshop will be held on Friday, October 12 at the Jackson Laboratory. 

You can visit the [workshop website ](https://smcclatchy.github.io/2018-10-12-bioconductor-bh/)for more information.
To preview the training material, visit [The Bioconductor 2018 Workshop Compilation](https://bioconductor.github.io/BiocWorkshops/).

R proficiency is a prerequisite. This prerequisite can be met by attending a two-day workshop in [R for Reproducible Scientific Analysis on Oct 11-12](https://smcclatchy.github.io/2018-10-10-r-bh/).

**Comment by annat22** [comment]
Hi Sue, Can I attend remotely? what is the schedule?

**Comment by smcclatchy** [comment]
Hi Annat,

I'll ask the other instructors if they are comfortable teaching both remotely and also to people in the room. The workshop website is here: https://smcclatchy.github.io/2018-10-12-bioconductor-bh/

Sue
