### ISSUE TITLE
Bioconductor Workshop

### ISSUE THREAD

**Issue by smcclatchy** [smcclatchy/studyGroup#76]
This one-day workshop will teach differential expression analysis and variant annotation using R and BioConductor. The workshop will be held on Wednesday, October 17 at the Jackson Laboratory for Genomic Medicine in Farmington, Connecticut. 

You can visit the [workshop website ](https://smcclatchy.github.io/2018-10-17-bioconductor-ct/)for more information.
To preview the training material, visit [The Bioconductor 2018 Workshop Compilation](https://bioconductor.github.io/BiocWorkshops/).

R proficiency is a prerequisite. This prerequisite can be met by attending a two-day workshop in [R for Reproducible Scientific Analysis on Oct 15-16](https://smcclatchy.github.io/2018-10-15-r-ct/). Please note that the R workshop will be held at 195 Farmington Ave, not at the Jackson Laboratory for Genomic Medicine.

**Comment by luissv7** [comment]
Hi Sue,
I would like to attend this one, but I cannot seem to find where you sign up for it. I accidentally signed up for the R for reproducible science workshop and just cancelled that one...
